steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "-v"]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/webapp:$TAG_NAME', '.']
  # Push to gcr
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/webapp:$TAG_NAME']