apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: webapp
description: main application pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles:
     - development
 - targetId: prod
   profiles:
     - production
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: development cluster
gke:
 cluster: projects/qwiklabs-gcp-01-83bdecd2196f/locations/us-central1-c/clusters/dev
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gke:
 cluster: projects/qwiklabs-gcp-01-83bdecd2196f/locations/us-central1-c/clusters/prod