apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: webapp
profiles:
  - name: development
    deploy:
      kustomize:
        paths:
          - kustomize/overlays/dev
  - name: production
    deploy:
      kustomize:
        paths:
          - kustomize/overlays/prod