apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts: 
  - image: gcr.io/qwiklabs-gcp-04-4e6e3f90ba5e/webapp
  local:
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
      - k8s/deployments/test.yaml