apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: webapp
# build:
#   artifacts:
#   - image: gcr.io/qwiklabs-gcp-03-de44ff6cd9ea/webapp
#     docker:
#       dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployments/test.yaml
    - k8s/services/test.yaml
