bases:
  - ../../application
patches:
  - replica_count.yaml
images:
  - name: us-central1-docker.pkg.dev/project-id/webapp-repo/webapp
    newName: us-central1-docker.pkg.dev/qwiklabs-gcp-00-9f067023a1f8/webapp-repo/webapp
    newTag: v1.0.40