apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-frontend-test
  name: webapp-frontend-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
  sessionAffinity: None
  type: LoadBalancer