kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-frontend-production
  labels:
    app: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: frontend
      labels:
        app: webapp
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/${parameters.project_id}/webapp-repo/webapp
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: frontend
        - name: VERSION
          value: production
        ports:
        - name: frontend
          containerPort: 8080