kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-frontend-test
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: frontend
      labels:
        app: webapp
        role: frontend
        env: testing
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/$PROJECT_ID/webapp-repo/webapp
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: frontend
          containerPort: 8080