apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-frontend-canary
  name: webapp-frontend-canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
    role: frontend
    env: canary
  sessionAffinity: None
  type: LoadBalancer
