apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-frontend-production
  name: webapp-frontend-production
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
    role: frontend
  sessionAffinity: None
  type: LoadBalancer